AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Web app with Cognito, Lambda, and CloudFront/S3 hosting

Resources:
  # Cognito User Pool
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: ARV
      AutoVerifiedAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
          RequireUppercase: true

  # Cognito User Pool Client
  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref CognitoUserPool
      ClientName: ARVUserPoolClient
      GenerateSecret: false
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - email
        - openid
        - profile
      CallbackURLs:
        - https://arv.geotales.io/signin
      LogoutURLs:
        - https://arv.geotales.io/signout

  # Cognito User Pool Domain
  CognitoUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: arv.geotales.io # Replace with your unique subdomain
      UserPoolId: !Ref CognitoUserPool

  # Lambda Function for Backend
  #BackendFunction:
  #  Type: AWS::Serverless::Function
  #  Properties:
  #    Handler: app.lambda_handler
  #    Runtime: python3.10
  #    CodeUri: backend/
  #    Policies:
  #      - AmazonRDSFullAccess
  #    Environment:
  #      Variables:
  #        COGNITO_USER_POOL_ID: !Ref CognitoUserPool
  #        COGNITO_USER_POOL_CLIENT_ID: !Ref CognitoUserPoolClient
  #
  #    Events:
  #      Api:
  #        Type: Api
  #        Properties:
  #          Path: /api/{proxy+}
  #          Method: ANY

  # S3 Bucket for Frontend Hosting
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-frontend-bucket # Replace with your desired bucket name
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

  # CloudFront Distribution
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !GetAtt FrontendBucket.WebsiteURL
            Id: S3Origin
            CustomOriginConfig:
              OriginProtocolPolicy: http-only
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        DefaultRootObject: index.html
        Enabled: true

Outputs:
  # Cognito Details
  UserPoolId:
    Value: !Ref CognitoUserPool
  UserPoolClientId:
    Value: !Ref CognitoUserPoolClient
  UserPoolDomain:
    Value: !Sub "https://${CognitoUserPoolDomain}.auth.${AWS::Region}.amazoncognito.com"

  # Lambda API Endpoint
  ApiEndpoint:
    Value: !Sub "https://${BackendFunction.ApiEndpoint}/api/"

  # S3 Website URL
  FrontendURL:
    Value: !Sub "https://${CloudFrontDistribution.DomainName}"
